# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Index generator
index_generator:
  order_by: order

# Site
title: Homepage of Chengbo Wang
subtitle: ''
description: ''
keywords:
author: Chengbo Wang
language: en
timezone: ''

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Academia
